---
- name: Install Gearman Libs
  yum: name={{ item }} state=latest
  with_items:    
    - uuid-devel
    - libuuid 
    - libuuid-devel 
    - uuid 
    - boost-devel 
    - libevent 
    - libevent-devel
    - gperf
    - boost   
    - boost-static
    - boost    
    - gcc-c++ 

- name: Get the Latest Gearman Job Server
  get_url: url=https://launchpad.net/gearmand/1.2/1.1.12/+download/gearmand-1.1.12.tar.gz dest=/tmp/

- name: go to folder untar
  command: chdir=/tmp tar -xvzf gearmand-1.1.12.tar.gz

- name: Configure
  command: chdir=/tmp/gearmand-1.1.12 ./configure

- name: Make Gearman
  command: chdir=/tmp/gearmand-1.1.12 make

- name: Make Install The Gearman
  command: chdir=/tmp/gearmand-1.1.12 make install

- name: Get the Latest Gearman  PECL Extension Gearman Client
  get_url: url=http://pecl.php.net/get/gearman dest=/tmp/

- name: go to folder untar
  command: chdir=/tmp tar -xvzf gearman-1.1.2.tgz

- name: Do Phpize Gearman
  command: chdir=/tmp/gearman-1.1.2 phpize

- name: Configure
  command: chdir=/tmp/gearman-1.1.2 ./configure

- name: Make Gearman
  command: chdir=/tmp/gearman-1.1.2 make

- name: Make Install The Gearman
  command: chdir=/tmp/gearman-1.1.2 make install

- name: Add gearman.so to php modules
  copy: src=gearman.ini dest=/etc/php.d/gearman.ini